sudo: false

language: node_js

node_js:
  - "5"
  - "6"

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache/yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  - npm config set spin false

install:
  - yarn

script:
  - yarn run build
